name: Build

on: [push]

jobs:

  build:
    name: Test, Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '14'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          cli: latest
          lein: latest

      - name: test
        run: lein test

      - name: build
        run: lein uberjar

      - uses: actions/upload-artifact@v1
        with:
          name: artifact
          path: target/
